In [ ]:
import sys
import numpy as np

Basic Numpy Arrays

In [4]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [5]:
a = np.array([1,2,3,4])

In [16]:
b = np.array([0., .5,1., 1.5, 2.])

In [17]:
a[0], a[1]

(1, 2)

In [18]:
a[0:]

array([1, 2, 3, 4])

In [19]:
a[1:3]

array([2, 3])

In [20]:
a[1:-1]

array([2, 3])

In [21]:
a[::2]

array([1, 3])

In [22]:
b

array([0. , 0.5, 1. , 1.5, 2. ])

In [23]:
b[0], b[2], b[-1]

(0.0, 1.0, 2.0)

In [25]:
b[[0,2,-1]]

array([0., 1., 2.])

Array Types

In [26]:
a

array([1, 2, 3, 4])

In [27]:
a.dtype

dtype('int32')

In [28]:
a.dtype

dtype('int32')

In [31]:
np.array([1,2,3,4], dtype=np.float64)

array([1., 2., 3., 4.])

In [33]:
np.array([1,2,3,4], dtype=np.int8)

array([1, 2, 3, 4], dtype=int8)

In [34]:
c = np.array(['a', 'b', 'c'])

In [35]:
c.dtype

dtype('<U1')

In [36]:
d = np.array([{'a': 1}, sys])

In [38]:
d.dtype

dtype('O')

Dimensions and shapes

In [39]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

In [40]:
A.shape

(2, 3)

In [41]:
A.ndim

2

In [42]:
A.size

6

In [44]:
B = np.array([
    [
        [12,11,10],
        [9,8,7]
    ],
    [
        [6,5,4],
        [3,2,1]
    ]
])

In [45]:
B.shape

(2, 2, 3)

In [46]:
B.ndim

3

In [48]:
B.size

12

In [52]:
C = np.array([
    [
        [12,11,10],
        [9,8,7]
    ],
        [6,5,4]
])

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

Indexing and Slicing of Matrices

In [54]:
# Square matrix
A = np.array([ 
#    0.1.2
    [1,2,3], # 0
    [4,5,6], # 1
    [7,8,9]  # 2
])

In [55]:
A[1]

array([4, 5, 6])

In [56]:
A[1][0]

4

In [57]:
# A[d1, d2, d3, d4]

In [58]:
A[1,0]

4

In [59]:
A[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [60]:
A[:, :2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [61]:
A[:2, :2]

array([[1, 2],
       [4, 5]])

In [62]:
A[:2, 2:]

array([[3],
       [6]])

In [63]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [64]:
A[1] = np.array([10,10,10])

In [65]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [ 7,  8,  9]])

In [66]:
A[2] = 99

In [67]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [99, 99, 99]])

Summary Statistics

In [68]:
a = np.array([1,2,3,4])

In [69]:
a.sum()

10

In [70]:
a.mean()

2.5

In [71]:
a.std()

1.118033988749895

In [72]:
a.var()

1.25

In [81]:
A = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [75]:
A.sum()

45

In [76]:
A.mean()

5.0

In [77]:
A.std()

2.581988897471611

In [78]:
A.sum(axis=0)

array([12, 15, 18])

In [79]:
A.sum(axis=1)

array([ 6, 15, 24])

In [83]:
A.mean(axis=0)

array([4., 5., 6.])

In [84]:
A.std(axis=0)

array([2.44948974, 2.44948974, 2.44948974])

In [85]:
A.std(axis=1)

array([0.81649658, 0.81649658, 0.81649658])

Broadcasting and Vectorirized operations

In [98]:
a = np.arange(4)

In [99]:
a

array([0, 1, 2, 3])

In [100]:
a + 10

array([10, 11, 12, 13])

In [101]:
a * 10

array([ 0, 10, 20, 30])

In [102]:
a

array([0, 1, 2, 3])

In [103]:
a += 100

In [104]:
a

array([100, 101, 102, 103])

In [105]:
l = [0, 1, 2, 3]

In [106]:
[ i * 10 for i in l]

[0, 10, 20, 30]

In [107]:
a = np.arange(4)

In [108]:
a

array([0, 1, 2, 3])

In [109]:
b = np.array([10, 10, 10, 10])

In [110]:
a + b

array([10, 11, 12, 13])

In [111]:
a * b

array([ 0, 10, 20, 30])

Boolean Arrays (also called masks)

In [112]:
a = np.arange(4)

In [113]:
a

array([0, 1, 2, 3])

In [114]:
a[[0, -1]]

array([0, 3])

In [115]:
a[[True, False, False, True]]

array([0, 3])

In [118]:
a

array([0, 1, 2, 3])

In [117]:
a >= 2

array([False, False,  True,  True])

In [120]:
a[a >= 2]

array([2, 3])

In [121]:
a.mean()

1.5

In [122]:
a[a > a.mean()]

array([2, 3])

In [124]:
a[~(a > a.mean())]

array([0, 1])

In [125]:
a[(a == 0) | (a == 1)]

array([0, 1])

In [126]:
a[(a <= 2) & (a % 2 == 0 )]

array([0, 2])

In [127]:
A = np.random.randint(100, size=(3, 3))

In [128]:
A

array([[37, 81, 37],
       [98, 75, 80],
       [26, 82, 83]])

In [131]:
A[np.array([
    [True, False, True],
    [False, True, False],
    [True, False, True]
])]

array([37, 37, 75, 26, 83])

In [132]:
A > 30

array([[ True,  True,  True],
       [ True,  True,  True],
       [False,  True,  True]])

In [133]:
A[A > 30]

array([37, 81, 37, 98, 75, 80, 82, 83])

Linear Algebra

In [134]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [135]:
B = np.array([
    [6, 5],
    [4, 3],
    [2, 1]
])

In [136]:
A.dot(B)

array([[20, 14],
       [56, 41],
       [92, 68]])

In [137]:
A @ B

array([[20, 14],
       [56, 41],
       [92, 68]])

In [138]:
B.T

array([[6, 4, 2],
       [5, 3, 1]])

In [139]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [140]:
B.T @ A

array([[36, 48, 60],
       [24, 33, 42]])

Size of objects in Memory

int, floats

In [141]:
# An integer in Python os > 24 bytes
sys.getsizeof(1)

28

In [142]:
# Longs are even larger
sys.getsizeof(10**100)

72

In [145]:
# Numpy size is much smaller
np.dtype(np.int8).itemsize

1

In [144]:
np.dtype(float).itemsize

8

Lists are even larger

In [146]:
# A one-element list
sys.getsizeof([1])

64

In [147]:
# An array of one element in numpy
np.array([1]).nbytes

4

And performance is also important

In [157]:
l = list(range(100000))

In [158]:
a = np.arange(100000)

In [159]:
%time np.sum(a ** 2)

CPU times: total: 0 ns
Wall time: 1 ms


216474736

In [160]:
%time sum([x ** 2 for x in l])

CPU times: total: 0 ns
Wall time: 5.54 ms


333328333350000

Useful Numpy functions

random

In [161]:
np.random.random(size=2)

array([0.90404927, 0.66308334])

In [162]:
np.random.normal(size=2)

array([ 0.51209347, -0.69200599])

In [163]:
np.random.rand(2, 4)

array([[0.98575003, 0.29542671, 0.64751598, 0.11999249],
       [0.44083762, 0.99230081, 0.13485109, 0.1927429 ]])

arange

In [164]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [165]:
np.arange(5, 10)

array([5, 6, 7, 8, 9])

In [166]:
np.arange(0, 1, .1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

reshape

In [167]:
np.arange(10).reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [169]:
np.arange(10).reshape(5, 2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

linspace

In [170]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [171]:
np.linspace(0, 1, 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [172]:
np.linspace(0, 1, 20, False)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

zeros, ones, empty

In [173]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [175]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [177]:
np.zeros((3, 3), dtype=np.int8)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int8)

In [179]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [181]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [180]:
np.empty(5)

array([1., 1., 1., 1., 1.])

In [182]:
np.empty((2 ,2))

array([[0.25, 0.5 ],
       [0.75, 1.  ]])

identity and eye

In [183]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [184]:
np.eye(3, 3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [185]:
np.eye(8, 4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [186]:
np.eye(8, 4, k=1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [187]:
np.eye(8, 4, k=-3)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [188]:
"Hello World"[6]

'W'